CREATE TABLE LIB_INFO(
	ID VARCHAR(20) NOT NULL,
	NAME VARCHAR(20) NOT NULL,
	BIRTH DATE NOT NULL,
	GENDER VARCHAR(20) NOT NULL,
	JOB VARCHAR(20),
	PHONE VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	ADDRESS VARCHAR(200) NOT NULL,
	HANDICAP INT,
	J_PART VARCHAR(50),
	J_LEVEL VARCHAR(50),
	JOINDATE TIMESTAMP DEFAULT NOW() NOT NULL,
	ROLE VARCHAR(50) DEFAULT 'ROLE_SEMIUSER' NOT NULL,
	
	CONSTRAINT FOREIGN KEY(ID) REFERENCES MEMBER(ID) ON UPDATE CASCADE ON DELETE CASCADE
)

DROP TABLE LIB_INFO
SELECT * FROM LIB_INFO
-----------------------------------

ID - 아이디
NAME - 이름
BIRTH - 생년월일(2000-01-01)
GENDER - 성별
JOB - 직업
PHONE - 전화번호
EMAIL - 이메일
ADDRESS - 주소
HANDICAP - 장애여부(1정상/-1장애)
J_PART - 부서
J_LEVEL - 직급
JOINDATE - 가입일
ROLE - 권한(시큐리티)

도서관 사용자/관리자 공통으로 해당되는사항만 NOT NULL