CREATE TABLE LIB_MEMBER(
	ID VARCHAR(20) NOT NULL,
	PWD VARCHAR(100) NOT NULL,
	ENABLED BOOLEAN DEFAULT TRUE NOT NULL,
	
	CONSTRAINT PRIMARY KEY(ID)
)

DROP TABLE LIB_MEMBER
SELECT * FROM LIB_MEMBER

-----------------------------------

ID - 아이디
PWD - 비밀번호
ENABLED - 사용권한(시큐리티 튜닝없이 그냥 사용하기위해)